version: '3.8'

services:
  mysql:
    image: mysql:8.0-oraclelinux9
    container_name: agenda_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda_db
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: